name: on-release


on:
  release:
    types:
      - published


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: "win32-x86"
            os: windows-latest
            arch: x86
          - name: "win32-amd64"
            os: windows-latest
            arch: AMD64
          - name: "win32-arm64"
            os: windows-latest
            arch: ARM64

          - name: "macos-x84_64"
            os: macos-latest
            arch: x86_64
          - name: "macos-arm64"
            os: macos-latest
            arch: arm64
          - name: "macos-universal2"
            os: macos-latest
            arch: universal2

          - name: "linux-i386"
            os: ubuntu-latest
            arch: i686
            platform: i386
          - name: "linux-x86_64"
            os: ubuntu-latest
            arch: x86_64
            platform: x86_64
          - name: "linux-aarch64"
            os: ubuntu-latest
            arch: aarch64
            platform: aarch64
          - name: "linux-ppc64le"
            os: ubuntu-latest
            arch: ppc64le
            platform: ppc64le
          - name: "linux-s390x"
            os: ubuntu-latest
            arch: s390x
            platform: s390x

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Set up QEMU
        if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.config.platform }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ARCHS: ${{ matrix.config.arch }}
          CIBW_ENVIRONMENT: CIBW_MC_NAME=${{ matrix.config.name }}
          # CI env var isn't present in Linux since it's emulated
          CIBW_ENVIRONMENT_LINUX: CI=1 CIBW_MC_NAME=${{ matrix.config.name }}

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.config.name }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pyproject.toml requirements
        shell: bash
        run: |
          python -m pip install toml
          python -c 'import toml; c = toml.load("pyproject.toml"); print("\n".join(c["build-system"]["requires"]))' \
            | python -m pip install -r /dev/stdin

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-source
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: artifact
          pattern: artifact-*
          delete-merged: 'true'

      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
